name = "report"
version = "1.0.0"
description = "Create informative & beautiful source code reports."
licences = ["Apache-2.0"]
repository = { type = "github", user = "MystPi", repo = "report" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
term_size = ">= 1.0.1 and < 2.0.0"
gleam_community_ansi = ">= 1.4.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.3 and < 2.0.0"
